vehicle_tracking_system1/routes/admin.py
from flask import Blueprint, render_template, redirect
from flask import jsonify, request
import traceback
import psycopg2
from utils.utils import convert_jsonb_to_list, auth


admin_view = Blueprint('admin_routes', __name__, template_folder='../templates')  

@admin_view.route('/')
def home():
    # return render_template('home.html')
    return render_template('home.html')

@admin_view.route('/firstpage')
def firstpage():
    # return render_template('home.html')
    return render_template('firstpage.html')


@admin_view.route('/login', methods=['GET','POST'])
def login():
	if request.method == 'POST':
		_form = request.form
		username = str(_form["username"])
		password = str(_form["password"])

		if len(username)<1 or len(password)<1:
			return render_template('login.html', error="Email and password are required")
		
        
        # d = user_manager.signin(email, hash(password))

		if auth( username, password):
			return redirect("/firstpage")
        

		return render_template('login.html', error="Email or password incorrect")


	return render_template('login.html')



@admin_view.route('/get_locations', methods=['POST'])
def get_locations():
    try:
        # Connect to PostgreSQL database
        with psycopg2.connect(
                user="postgres",
                password="rvce1234",
                host="database-1.cnco44k2w5r9.ap-south-1.rds.amazonaws.com",
                port=5432,
                database="postgres"
        ) as connection:
            with connection.cursor() as cursor:
                vehicle_id = request.form.get('vehicle_id')
                date = request.form.get('date')
                # Using .format() to dynamically inject table name and date into the query
                query = "SELECT location_data FROM {} WHERE date = '{}'".format(vehicle_id, date)
                cursor.execute(query)
                records = cursor.fetchall()
                converted_data = convert_jsonb_to_list(records[0])
        return jsonify(converted_data)
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": "Internal Server Error"}), 500



@admin_view.route('/map', methods=['GET', 'POST'])
def map():
    try:
        vehicle_id = request.form.get('vehicle_id')
        return render_template('map.html', vehicle_id=vehicle_id)
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": "Internal Server Error"}), 500

vehicle_tracking_system1/templates/firstpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SignInPage</title>
    <link rel="stylesheet" type="text/css" href="../static/styles/style.css" />
  
  
  </head>
  <body>
    <div class="container">
      
      <div class="forms-container">
        <h1 class="header">Vechile Tracking System</h1>
        <div class="signin-signup">
          
          <form onsubmit="return submitForm()" class="sign-in-form" method="post">
            
            <h2 class="title">Enter Vechile Details</h2>
            <div class="input-field">
              <i class="fas fa-user"></i>
              <label for="vehicle_input">Vehicle:</label>
              <input type="text" id="vehicle_input" name="vehicle_name" required/>
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <label for="date_input">Date:</label>
                <input type="date" id="date_input" name="date" required />

            </div>
            <input type="submit" value="Submit" class="btn solid" />
          </form>

        <p id="errorMessage" class="error-message"></p>
        </div>
        
      </div>
      <div class="panels-container">

        <div class="panel left-panel">
            <div class="content">
                <h3>Vechile Tracking System</h3>
                <p>Track your vechile from anywhere and anytime</p>
                <button class="btn transparent" id="sign-up-btn">Know More</button>
                <div id="more-info" style="display: none; margin-top: 20px;">
                  <p>The Vehicle Tracking System allows you to monitor the location, speed, and status of your vehicles in real-time. Ensure the safety and efficiency of your fleet with our advanced tracking technology.</p>
                </div>
            </div>
            <img src="./img/GPS.jpg"  id="imgprop" class="image" alt="">
        </div>
      </div>
      
    </div>

    <script src="../static/scripts/app.js"></script>
  </body>
</html>

vehicle_tracking_system1/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HomePage</title>
    <link rel="stylesheet" type="text/css" href="../static/styles/style1.css" />
  </head>
  <body>
    <div class="container">
      <header class="header">
        <h1>Vehicle Tracking System</h1>
        <button class="btn transparent" id="login-btn">Login</button>
      </header>
      
      <div class="content">
        <img src="./img/GPS.jpg" id="imgprop" class="image" alt="Vehicle Tracking System Image" />
        <div style="margin-top: 20px;">
          <p>The Vehicle Tracking System allows you to monitor the location, speed, and status of your vehicles in real-time. Ensure the safety and efficiency of your fleet with our advanced tracking technology.</p>
        </div>
      </div>
    </div>

    <script>
      const loginBtn = document.getElementById("login-btn");
      loginBtn.addEventListener("click", () => {
        window.location.href = "/login";
      });
    </script>
  </body>
</html>

vehicle_tracking_system1/templates/login.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SignInPage</title>
        <link rel="stylesheet" type="text/css" href="../static/styles/style.css" />
    
    
    </head>
    <body>
        <div class="container">
        
        <div class="forms-container">
            <h1 class="header">Vechile Tracking System</h1>
            <div class="signin-signup">

                        <!-- Display error message if it exists -->
            {% if error %}
                <div class="error-message">{{ error }}</div>
            {% endif %}
            <form action="{{url_for('admin_routes.login')}}" class="sign-in-form" method="post">
                
                <h2 class="title">Sign In</h2>
                <div class="input-field">
                <i class="fas fa-user"></i>
                <input name="username" type="text" placeholder="Username" />
                </div>
                <div class="input-field">
                <i class="fas fa-lock"></i>
                <input name="password" type="password" placeholder="Password" />
                </div>
                <input type="submit" value="Login" class="btn solid" />
            </form>


            
            </div>
        </div>
        <div class="panels-container">

            <div class="panel left-panel">
                <div class="content">
                    <h3>Vechile Tracking System</h3>
                    <p>Track your vechile from anywhere and anytime</p>
                    <button class="btn transparent" id="sign-up-btn">Know More</button>
                    <div id="more-info" style="display: none; margin-top: 20px;">
                    <p>The Vehicle Tracking System allows you to monitor the location, speed, and status of your vehicles in real-time. Ensure the safety and efficiency of your fleet with our advanced tracking technology.</p>
                    </div>
                </div>
                <img src="./img/GPS.jpg"  id="imgprop" class="image" alt="">
            </div>
        </div>
        
        </div>

        <script src="./scripts/app.js"></script>
    </body>
</html>